### ISSUE TITLE
No License

### ISSUE THREAD

**Issue by Lokathor** [ColinEberhardt/wasm-rust-chip8#4]
Your repo has no licensing information. It can just be public domain if you'd like, but you still have to say that somewhere.

**Comment by ColinEberhardt** [comment]
Oops - my bad. I've added an MIT licence https://github.com/ColinEberhardt/wasm-rust-chip8/commit/4810ab6e36c0d89f81d80bbf5c12ee20de088243. Thanks for pointing this out!
